# ruff: noqa
"""Temporary docstring."""
# Generated by Django 5.0.3 on 2026-04-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "robot_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status", models.CharField(default="UNKNOWN", max_length=50)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="robots.robot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battery_lvl", models.FloatField()),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="robots.robot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["robot", "-timestamp"],
                        name="robots_tele_robot_i_98049e_idx",
                    )
                ],
            },
        ),
    ]
