# ruff: noqa
"""Temporary docstring."""
# Generated by Django 5.0.3 on 2026-04-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("avg_battery", models.FloatField()),
                ("min_battery", models.FloatField()),
                ("max_battery", models.FloatField()),
                ("message_count", models.IntegerField()),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="robots.robot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry daily stats",
                "unique_together": {("robot", "date")},
            },
        ),
    ]
