[pytest]
DJANGO_SETTINGS_MODULE = telemetry_core.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --nomigrations -p no:warnings
testpaths = tests
# Добавляем подпапки в путь, чтобы относительные импорты работали
pythonpath = backend tests/unit/backend tests/integration/backend tests/unit/simulator
